### PR TITLE
Update Accordion example

### PR DESCRIPTION
**Pull request by kdo**
- Update example to include nested accordion
- Add note about nested accordion in code section

Related issues:
https://github.com/10up/component-accordion/issues/28

Related PRs:
https://github.com/10up/component-accordion/pull/30
https://github.com/10up/component-accordion/pull/32

### CODE REVIEW

**Review by timwright12 — APPROVED** [review]

**Comment by timwright12** [comment]
@kdo let me know when you're ready to merge this one

**Comment by jeffpaul** [comment]
@kdo any updates on being able to finalize this PR so it can get through review and merged in?

**Comment by kdo** [comment]
@jeffpaul sorry totally forgot this one! It's ready to go! :)

**Comment by jeffpaul** [comment]
@timwright12 over to you then for final review/merging.

**Pull request merged**
